In [6]:
import psycopg2
from datetime import datetime
from psycopg2 import sql
import requests
from sentence_transformers import SentenceTransformer
import openai

def create_conn_source(select_query):
    conn = None
    try:
        conn = psycopg2.connect(
            host="ep-still-hat-a195lqjj.ap-southeast-1.aws.neon.tech",
            database="neondb",
            user="neondb_owner",
            password="UPEwCcuev9A3"
        )
        cur = conn.cursor()
        cur.execute(select_query)
        rows = cur.fetchall()
        cur.close()
        return rows
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

def update_conn_source(update_query):
    conn = None
    try:
        conn = psycopg2.connect(
            host="ep-still-hat-a195lqjj.ap-southeast-1.aws.neon.tech",
            database="neondb",
            user="neondb_owner",
            password="UPEwCcuev9A3"
        )
        cur = conn.cursor()
        cur.execute(update_query)
        conn.commit()
        cur.close()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

def insert_conn_source(insert_query, data):
    conn = None
    try:
        conn = psycopg2.connect(
            host="ep-still-hat-a195lqjj.ap-southeast-1.aws.neon.tech",
            database="neondb",
            user="neondb_owner",
            password="UPEwCcuev9A3"
        )
        cur = conn.cursor()
        for item in data:
            #print(item)
            cur.execute(insert_query, item)
        conn.commit()
        cur.close()
        # print("Data inserted successfully")
        return True
    except (Exception, psycopg2.DatabaseError) as error:
        # print(error)
        return False
    finally:
        if conn is not None:
            conn.close()
        return False

def create_conn_source2(select_query):
    conn = None
    try:
        conn = psycopg2.connect(
            host="ep-spring-pine-a1906lg2.ap-southeast-1.aws.neon.tech",
            database="neondb",
            user="neondb_owner",
            password="4QbNXc9vlAYi"
        )
        cur = conn.cursor()
        cur.execute(select_query)
        rows = cur.fetchall()
        cur.close()
        return rows
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

def update_conn_source2(update_query):
    conn = None
    try:
        conn = psycopg2.connect(
            host="ep-spring-pine-a1906lg2.ap-southeast-1.aws.neon.tech",
            database="neondb",
            user="neondb_owner",
            password="4QbNXc9vlAYi"
        )
        cur = conn.cursor()
        cur.execute(update_query)
        conn.commit()
        cur.close()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

def insert_conn_source2(insert_query, data):
    conn = None
    try:
        conn = psycopg2.connect(
            host="ep-spring-pine-a1906lg2.ap-southeast-1.aws.neon.tech",
            database="neondb",
            user="neondb_owner",
            password="4QbNXc9vlAYi"
        )
        cur = conn.cursor()
        for item in data:
            #print(item)
            cur.execute(insert_query, item)
        conn.commit()
        cur.close()
        # print("Data inserted successfully")
        return True
    except (Exception, psycopg2.DatabaseError) as error:
        # print(error)
        return False
    finally:
        if conn is not None:
            conn.close()
        return False

def select_conn_destination(select_query):
    conn = None
    try:
        conn = psycopg2.connect(
            host="aws-0-ap-south-1.pooler.supabase.com",
            database="postgres",
            user="postgres.icrispjgfllulboelvhw",
            password="rJywtQ5R2Wt17hG1",
            port=6543
        )
        cur = conn.cursor()
        cur.execute(select_query)
        rows = cur.fetchall()
        cur.close()
        return rows
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

def create_conn_destination(insert_query, data):
    conn = None

    try:
        conn = psycopg2.connect(
            host="aws-0-ap-south-1.pooler.supabase.com",
            database="postgres",
            user="postgres.icrispjgfllulboelvhw",
            password="rJywtQ5R2Wt17hG1",
            port=6543
        )
        cur = conn.cursor()
        for item in data:
            #print(item)
            cur.execute(insert_query, item)
        conn.commit()
        cur.close()
        # print("Data inserted successfully")
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

def update_conn_destination(update_query):
    conn = None

    try:
        conn = psycopg2.connect(
            host="aws-0-ap-south-1.pooler.supabase.com",
            database="postgres",
            user="postgres.icrispjgfllulboelvhw",
            password="rJywtQ5R2Wt17hG1",
            port=6543
        )
        cur = conn.cursor()
        cur.execute(update_query)
        conn.commit()
        cur.close()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        if conn is not None:
            conn.close()

In [3]:


articles_l2 = """
SELECT
    a.tag_id,
    a.tag,
    a.language,
    a.tag_hierachy
FROM
    synopse_articles.t_v4_tags_hierarchy_all_language a;
"""
articles_l2_output = create_conn_source(articles_l2)
    
t_v4_tags_hierarchy_insert_query ="""
INSERT INTO synopse_articles.t_v10_tags_all_languages (
    tag_id,
    tag,
    language,
    tag_hierachy
) VALUES (%s, %s, %s, %s)  ON CONFLICT DO NOTHING;
"""
insert_conn_source2(t_v4_tags_hierarchy_insert_query, articles_l2_output)

False

In [9]:


articles_l2 = """
SELECT
    a.id,
    a.tag,
    a.tag_hierachy,
    a.tag_description,
    a.tag_tel,
    a.tag_de,
    a.tag_tam,
    a.tag_hin
FROM
    synopse_articles.t_v4_tags_hierarchy a where a.is_valid = 1;
"""
articles_l2_output = create_conn_source(articles_l2)

t_v4_tags_hierarchy_insert_query ="""
INSERT INTO synopse_articles.t_v4_tags_hierarchy (
    tag_id,
    tag,
    tag_hierachy,
    tag_description,
    tag_tel,
    tag_de,
    tag_tam,
    tag_hin
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)  ON CONFLICT DO NOTHING;
"""
create_conn_destination(t_v4_tags_hierarchy_insert_query, articles_l2_output)

[(518, 'Arts & Design', 1, 'News related to visual arts, architecture, design, and creative endeavors.', 'కళలు & రూపకల్పన', 'Kunst & Design', 'கலை & வடிவமைப்பு', 'कला और डिजाईन'), (519, 'Business & Economy', 1, 'Coverage of financial markets, business trends, economic policies, and corporate developments.', 'వ్యాపారం & ఆర్థిక వ్యవస్థ', 'Wirtschaft & Finanzen', 'வ్యాபாரம் & பொருளாதாரம்', 'व्यापार और अर्थव्यवस्था'), (531, 'Society & Culture', 1, 'Coverage of social issues, cultural events, societal trends, and human interest stories.', 'సమాజం & సంస్కృతి', 'Gesellschaft & Kultur', 'சமூகம் & பண்பாடு', 'समाज और संस्कृति'), (533, 'Startups', 1, 'News about new business ventures, entrepreneurial innovations, and startup ecosystem developments.', 'స్టార్టప్\u200c', 'Startups', 'தொடக்கங்கள்', 'स्टार्टअप'), (534, 'Technology', 1, 'Coverage of tech industry news, gadgets, software, innovations, and digital trends.', 'టెక్నాలజీ', 'Technologie ', 'தொழில்நுட்பம்', 'प्रौद्योगिकी '), (520, 'Education', 1, 'News about educational institutions, policies, innovations, and trends in learning.', 'విద్య', 'Bildung', 'கல்வி', 'शिक्षा'), (521, 'Entertainment', 1, 'Updates on movies, music, celebrities, TV shows, and other forms of entertainment.', 'వినోదం', 'Unterhaltung', 'பொழுதுபோக்கு', 'मनोरंजन'), (522, 'Fashion', 1, 'News regarding fashion trends, designers, brands, and the fashion industry.', 'ఫ్యాషన్', 'Mode', 'பேஷன்', 'फैशन'), (523, 'Food & Drinks', 1, 'Coverage of culinary arts, food culture, recipes, dining trends, and beverage industry news.', 'ఆహారం & పానీయాలు ', 'Essen & Trinken', 'உணவு & பானங்கள்', 'खाना पानी'), (524, 'Gaming', 1, 'News related to video games, gaming industry developments, esports, and gaming culture.', 'గేమింగ్', 'Gaming', 'கேமிங் ', 'गेमिंग'), (525, 'Health', 1, 'Updates on medical research, healthcare policies, wellness trends, and public health issues.', 'ఆరోగ్యం', 'Gesundheit', 'ஆரோக்கியம்', 'स्वास्थ्य '), (526, 'Home & DIY', 1, 'Coverage of home improvement, interior design, do-it-yourself projects, and household tips.', 'ఇల్లు & DIY', 'Haus & Garten', 'வீடு & DIY', 'घर और DIY'), (527, 'Lifestyle', 1, 'News encompassing various aspects of lifestyle including fashion, health, travel, and leisure.', 'జీవన శైలి', 'Lebensstil', 'வாழ்க்கை முறை ', 'जीवन शैली '), (528, 'Personal Growth', 1, 'Articles focused on self-improvement, personal development, productivity, and mindfulness.', 'వ్యక్తిగత అభివృద్ధి', 'Persönliches Wachstum', 'தனிப்பட்ட வளர்ச்சி', 'व्यक्तिगत विकास '), (529, 'Politics', 1, 'Updates on government policies, political developments, elections, and international relations.', 'రాజకీయాలు ', 'Politik', 'அரசியல்', 'राजनीति '), (530, 'Science', 1, 'News about scientific discoveries, breakthroughs, research findings, and advancements in various fields of science.', 'శాస్త్రం', 'Wissenschaft ', 'அறிவியல்', 'विज्ञान '), (532, 'Sports', 1, 'Updates on sports events, athletes, teams, scores, and sports industry news.', 'క్రీడలు', 'Sport ', 'விளையாட்டு', 'खेल '), (535, 'Travel', 1, 'Updates on travel destinations, tips, tourism trends, and adventure experiences.', 'ప్రయాణం', 'Reisen', 'பயணம்', 'यात्रा'), (536, 'World Affairs', 1, 'News concerning international affairs, global politics, diplomacy, and geopolitical events.', 'ప్రపంచ వ్యవహారాలు', 'Weltgeschehen', 'உலக விவகாரங்கள்', 'यात्राविश्व मामले')]

In [11]:


articles_l2 = """
SELECT
    a.tag_id,
    a.language,
    a.tag,
    a.tag_hierachy
FROM
    synopse_articles.t_v4_tags_all_languages a;
"""
articles_l2_output = create_conn_source(articles_l2)

t_v4_tags_hierarchy_insert_query ="""
INSERT INTO synopse_articles.t_v4_tags_all_languages (
    tag_id,
    language,
    tag,
    tag_hierachy
) VALUES (%s, %s, %s, %s)  ON CONFLICT DO NOTHING;
"""
create_conn_destination(t_v4_tags_hierarchy_insert_query, articles_l2_output)

In [12]:
    
while True:
    articles_l2_details = """
    SELECT 
        a.article_group_id,
        a.title,
        a.summary,
        a.is_valid,
        a.image_urls,
        a.logo_urls,
        a.summary_60_words,
        a.keywords_tags,
        a.location_tags,
        a.org_tags,
        a.person_tags,
        b.tag,
        a.group_ai_tags_l3,
        a.tag_id,
        a.is_audio_created_valid,
        a.llm_keypoints,
        a.post_published
    FROM 
        synopse_articles.t_v4_article_groups_l2_detail a, synopse_articles.t_v4_tags_all_languages b
    WHERE 
        a.prod = 0 AND b.tag_id != 0 AND a.logo_urls is not null and b.tag_id = a.tag_id and a.language = b.language
        ORDER BY 
            a.id DESC
        LIMIT 200;
    """
    articles_l2_details_output = create_conn_source(articles_l2_details)
    if len(articles_l2_details_output) == 0:
        break
    articles_l2_details_insert_query ="""
    INSERT INTO synopse_articles.t_v4_article_groups_l2_detail (
        article_group_id,
        title,
        summary,
        is_valid,
        image_urls,
        logo_urls,
        summary_60_words,
        keywords_tags,
        location_tags,
        org_tags,
        person_tags,
        group_ai_tags_l3,
        group_ai_tags_l2,
        tag_id,
        is_audio_created_valid,
        keypoints,
        post_published
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)  
    ON CONFLICT(article_group_id)
    DO UPDATE SET 
        title = EXCLUDED.title,
        summary = EXCLUDED.summary,
        is_valid = EXCLUDED.is_valid,
        image_urls = EXCLUDED.image_urls,
        logo_urls = EXCLUDED.logo_urls,
        summary_60_words = EXCLUDED.summary_60_words,
        keywords_tags = EXCLUDED.keywords_tags,
        location_tags = EXCLUDED.location_tags,
        org_tags = EXCLUDED.org_tags,
        person_tags = EXCLUDED.person_tags,
        group_ai_tags_l3 = EXCLUDED.group_ai_tags_l3,
        group_ai_tags_l2 = EXCLUDED.group_ai_tags_l2,
        tag_id = EXCLUDED.tag_id,
        is_audio_created_valid = EXCLUDED.is_audio_created_valid,
        keypoints = EXCLUDED.keypoints,
        post_published = EXCLUDED.post_published;
    """
    create_conn_destination(articles_l2_details_insert_query, articles_l2_details_output)
    ids = []
    for i in range(len(articles_l2_details_output)):
        ids.append(articles_l2_details_output[i][0])
    t_ids = tuple(ids)
    update_query = "UPDATE synopse_articles.t_v4_article_groups_l2_detail SET prod = 1 WHERE article_group_id IN " + str(t_ids) + ";"
    update_conn_source(update_query)

In [17]:
print(tags)

['Arts & Design', 'Business & Economy', 'Society & Culture', 'Startups', 'Technology', 'Education', 'Entertainment', 'Fashion', 'Food & Drinks', 'Gaming', 'Health', 'Home & DIY', 'Lifestyle', 'Personal Growth', 'Politics', 'Science', 'Sports', 'Travel', 'World Affairs']